### PR TITLE
Typescript Typings

### PR DESCRIPTION
**Pull request by TrevorDev**
PR for typing created by @sami-badawi and @geon 
Not sure if its complete but its better than nothing

https://github.com/greggman/twgl.js/issues/50

### CODE REVIEW

**Comment by greggman** [comment]
hey, sorry I haven't merged this yet.

I noticed `v3` was missing.

**Comment by geon** [comment]
I’ll be on an open-source hackathon in sept. Want me to take a look at it?

**Comment by geon** [comment]
Hi!

I have done some extensive changes to the typings in a separate pull request: https://github.com/greggman/twgl.js/pull/89

**Comment by geon** [comment]
@greggman And I added v3.

**Comment by TrevorDev** [comment]
@geon Thanks, Ill close this in favor of that

**Pull request closed without merging**
