### PR TITLE
new example: gpgpu / particles

### PR DESCRIPTION
**Pull request by munrocket**
exists bug with window resize.

### CODE REVIEW

**Comment by greggman** [comment]
Thanks!

manually merged

**Comment by munrocket** [comment]
It is a little not fair to merge manually, but I did not finish the pull request, yes.
In any case, this GPGPU topic is very interesting. I want to finish this and add it to your documentation.

**Comment by greggman** [comment]
> It is a little not fair to merge manually,

That's a normal part of using git. I'm not sure what you think is not fair. Your name/email is still on the commit.

> but I did not finish the pull request

Then you probably shouldn't have made a pull request or you should should have mentioned it wasn't ready. It's normal when someone gets a pull-request to assume it's actually a pull **request** 😛

Also if you don't want things manually merged then you need to clean up your pull requests. Ideally there should be just one commit. If there are multiple commits they should clean and feature based, not fixes

So for example

       commit 1 add sample
       commit 2 fix lint
       commit 3 modify sample
       commit 4 fix lint

Should be either just

      commit 1 add sample

or at worst

      commit 1 add sample
      commit 2 modify sample

If you're at stage 1

      git commit -m "add sample"
      git push origin branch-on-github

And you find a lint type of issue then

      git add file-with-issue-fixed
      git commit --amend
      git push --force origin branch-on-github

This way the history isn't full of minor fixes

You can also run `npm run pre-push` to check before pushing. As well you can add a file `<repo>/.git/hooks/pre-push` with this contents

```
#!/bin/sh
set -e
npm run pre-push
```

So you can check if you're going to get an error before pushing.

**Comment by munrocket** [comment]
>That's a normal part of using git. I'm not sure what you think is not fair. Your name/email is still on the commit.
Thanks for making it clear. I didn't know what is _manually_ mean :D

**Comment by munrocket** [comment]
>If there are multiple commits they should clean and feature based, not fixes

Ok, I will try it.

**Pull request closed without merging**
