### PR TITLE
update main for package.json

### PR DESCRIPTION
**Pull request by ajbeach2**
index.js doesn't exist, shouldn't this be dist/twgl-full.min.js?

### CODE REVIEW

**Comment by derhuerst** [comment]
Maybe the [non-minified file](dist/twgl-full.js) is a better choice since it is better for debugging and Node.js doesn't care about file size?

**Comment by greggman** [comment]
I guess i don't understand why you'd use twgl with node, unless it's in electron. So i assumed people using twgl with node must be using it to build JS for the browser?

**Comment by ajbeach2** [comment]
I'm using npm to manage packages.  I am using browseify and gulp to build
for the client.  This was because I wanted to use the node require syntax,
and for what I am building there is a backend component that uses node.

**Comment by greggman** [comment]
ok, I push 0.0.23 to npm. Try it out.

**Pull request merged**
